# py-temp-fork-pvt_merge_no_docker-def.yaml
name: Python Template Fork Merge With Docker

on:
  push:

jobs:
  python-template-fork-merge-with-docker:
    permissions:
      id-token: write
      contents: write
    #    if: github.event.pull_request.merged == true
    uses: BrightEdgeeServices/devops-automation/.github/workflows/py-wf-fork-merge_with_docker-def.yaml@master
    with:
      run_deploy: ${{ startsWith(github.ref, 'refs/tags/') == true }}
    # secrets: inherit
    secrets:
      GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER }}
      GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER }}
      INSTALLER_USER_ID:         ${{secrets.INSTALLER_USER_ID }}
      INSTALLER_USER_PWD:        ${{secrets.INSTALLER_USER_PWD }}
      MYSQL_DATABASE:            ${{secrets.MYSQL_DATABASE }}
      MYSQL_HOST:                ${{secrets.MYSQL_HOST }}
      MYSQL_PASSWORD:            ${{secrets.MYSQL_PASSWORD}}
      MYSQL_ROOT_PASSWORD:       ${{secrets.MYSQL_ROOT_PASSWORD}}
      MYSQL_TCP_PORT:            ${{secrets.MYSQL_TCP_PORT}}
      MYSQL_USER:                ${{secrets.MYSQL_USER}}
      PROJECT_NAME:              ${{secrets.PROJECT_NAME }}
#      RELEASE_EMAIL_USER:        ${{secrets.RELEASE_EMAIL_USER }}
#      RELEASE_EMAIL_PASSWORD:    ${{secrets.RELEASE_EMAIL_PASSWORD }}
